### PR TITLE
Add "nezu - modified".

### PR DESCRIPTION
**Pull request by michaellenaghan**
This will be a temporary addition; I've modified Nezu in various ways, and I'd like to switch my sites to the modified theme.

### CODE REVIEW

**Comment by michaellenaghan** [comment]
Once I've switch my sites to this theme, does it have to remain in the registry?

**Comment by lepture** [comment]
Hi @michaellenaghan 

You have to tag it with `0.1.0`. Typlog will search the template via "repo" and "version" according to your `theme.json`.

**Comment by michaellenaghan** [comment]
Of course! Sorry. Done.

**Comment by lepture** [comment]
And we now support using your own theme: https://typlog.com/changelog/use-own-theme

**Comment by michaellenaghan** [comment]
Thank you; I was successfully able to switch to the theme in my repository. Fantastic!

**Pull request closed without merging**
